version: "3.9"
networks:
  dapoa:
    external: true

services:
  signer_1:
    image: fgeth:latest
    environment:
      - NODE_TYPE=signer
      - SIGNER_ID=1
      - NETWORKD_ID=42342
    volumes:
      - ./signers:/signers
    networks:
      - dapoa
    ports:
      - 8000:40001 # ws port
      - 7000:6060
    hostname: signer_1

  signer_2:
    image: fgeth:latest
    environment:
      - NODE_TYPE=signer
      - SIGNER_ID=2
      - NETWORKD_ID=42342
    volumes:
      - ./signers:/signers
    hostname: signer_2
    networks:
      - dapoa
    ports:
      - 8001:40001
      - 7001:6060
  signer_3:
    image: fgeth:latest
    environment:
      - NODE_TYPE=signer
      - SIGNER_ID=3
      - NETWORKD_ID=42342
    volumes:
      - ./signers:/signers
    hostname: signer_3
    networks:
      - dapoa
    ports:
      - 8002:40001
      - 7002:6060
  signer_4:
    image: fgeth:latest
    environment:
      - NODE_TYPE=signer
      - SIGNER_ID=4
      - NETWORKD_ID=42342
    volumes:
      - ./signers:/signers
    hostname: signer_4
    networks:
      - dapoa
    ports:
      - 8003:40001
      - 7003:6060
  signer_5:
    image: fgeth:latest
    environment:
      - NODE_TYPE=signer
      - SIGNER_ID=5
      - NETWORKD_ID=42342
    volumes:
      - ./signers:/signers
    hostname: signer_5
    networks:
      - dapoa
    ports:
      - 8004:40001
      - 7004:6060
  signer_6:
    image: fgeth:latest
    environment:
      - NODE_TYPE=signer
      - SIGNER_ID=6
      - NETWORKD_ID=42342
    volumes:
      - ./signers:/signers
    hostname: signer_6
    networks:
      - dapoa
    ports:
      - 8005:40001
      - 7005:6060
  signer_7:
    image: fgeth:latest
    environment:
      - NODE_TYPE=signer
      - SIGNER_ID=7
      - NETWORKD_ID=42342
    volumes:
      - ./signers:/signers
    hostname: signer_7
    networks:
      - dapoa
    ports:
      - 8006:40001
      - 7006:6060
  signer_8:
    image: fgeth:latest
    environment:
      - NODE_TYPE=signer
      - SIGNER_ID=8
      - NETWORKD_ID=42342
    volumes:
      - ./signers:/signers
    hostname: signer_8
    networks:
      - dapoa
    ports:
      - 8007:40001
      - 7007:6060

  signer_9:
    image: fgeth:latest
    environment:
      - NODE_TYPE=signer
      - SIGNER_ID=9
      - NETWORKD_ID=42342
    volumes:
      - ./signers:/signers
    hostname: signer_9
    networks:
      - dapoa
    ports:
      - 8008:40001
      - 7008:6060
  signer_10:
    image: fgeth:latest
    environment:
      - NODE_TYPE=signer
      - SIGNER_ID=10
      - NETWORKD_ID=42342
    volumes:
      - ./signers:/signers
    hostname: signer_10
    networks:
      - dapoa
    ports:
      - 8009:40001
  signer_11:
    image: fgeth:latest
    environment:
      - NODE_TYPE=signer
      - SIGNER_ID=11
      - NETWORKD_ID=42342
    volumes:
      - ./signers:/signers
    hostname: signer_11
    networks:
      - dapoa
    ports:
      - 8010:40001
  signer_12:
    image: fgeth:latest
    environment:
      - NODE_TYPE=signer
      - SIGNER_ID=12
      - NETWORKD_ID=42342
    volumes:
      - ./signers:/signers
    hostname: signer_12
    networks:
      - dapoa
    ports:
      - 8011:40001
